대나무숲에서 나갔을때 스크롤이 유지되도록 변경하였습니다
jeamxn/dimigoin-pull-service pull request #162
Opened 2024-05-08 12:25 UTC by yeonfish6040

2024-05-09 00:56 UTC, jeamxn requested changes

2024-05-09 00:56 UTC, jeamxn commented on src/app/(login)/bamboo/[id]/page.tsx
> +            href={"/bamboo#"+data.number}
이거
```tsx
href={`/bamboo#${data.number}`}
```
로 수정해주면 넣어드릴게여

개발할 때 eslint키고 해주세여.. 포멧 안 맞으면 빌드할 때 오류 발생시킴

2024-05-09 10:53 UTC, yeonfish6040 commented on src/app/(login)/bamboo/[id]/page.tsx
> +            href={"/bamboo#"+data.number}
앗 넵...

2024-05-12 05:19 UTC, jeamxn approved these changes
👍👏

2024-05-12 05:21 UTC, merged

2024-05-12 05:27 UTC, jeamxn commented
근데 이거 넣어봤자 논리적으로 불가능한게 데이터가 fetch되기 전에 url로 스크롤 위치 찾는 셈이라 안 될 겁니당